services:
    backend:
        build:
            context: .
            target: production
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - HOST_OS=linux
        restart: unless-stopped
