services:
    backend:
        build:
            context: .
            target: production
        ports:
            - "3000:3000"
        env_file:
            - .env
        restart: unless-stopped
